name: blog_store
description: "Blog Store - E-Commerce app with Blogger backend schema inheritance."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  bloc_signals_flutter: ^0.1.6
  kaisel: ^0.0.5
  intl: ^0.20.2
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.31
  path_provider: ^2.1.5
  path: ^1.9.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_messaging: ^15.2.4
  google_sign_in: ^6.2.2
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
